defaults:
  - dataset@datasets.grandstaff: grandstaff_train
  - dataset@datasets.synth: synth_omr_500k_train
  - preprocessor: llava
  - _self_

disable_caching: True # override in cli

formatting:
  convert_to: "bekern"
