kind: "smt"
in_channels: 1
maxh: 2970
maxlen: 4353
maxw: 2100
d_model: 256
dim_ff: 1024
num_hidden_layers: 8
attn_heads: 8
use_flash_attn: false
pad_token_id: 0   # <PAD>
eos_token_id: 2   # <EOS>
decoder_start_token_id: 1  # <SEP>
vocab_size: ~ # filled from tokenizer at train time
