kind: "qwen25vl"

tokenizer:
  special_tokens: ["<PAD>", "<BOS>", "<SEP>", "<EOS>", "<IMG_PATCH>"]
  bos_token: "<BOS>"
  pad_token: "<PAD>"
  eos_token: "<EOS>"

image_processor:
  do_resize: True
  resample: 3 # PIL.Image.Resampling.BICUBIC
  temporal_patch_size: 2
  patch_size: 16
  merge_size: 2
  size:
    shortest_edge: 4096 # (32*32) * 4, min 4 image tokens per image
    longest_edge: 1310720 # (32*32) * 1280, max 1280 image tokens per image
  default_to_square: false
  do_convert_rgb: false
  do_rescale: True
  do_normalize: True
  image_mean: 0.5
  image_std: 0.5
